import { ReactNode } from 'react'
import './globals.css'
import { CreateToastProvider } from './Hooks/ToastContext'
import { CreateInputValueProvider } from './Hooks/InputValueContext'

export const metadata = {
  title: 'Formulário',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-br">
      <body className="overflow-y-hidden">
        <CreateToastProvider>
          <CreateInputValueProvider>{children}</CreateInputValueProvider>
        </CreateToastProvider>
      </body>
    </html>
  )
}
