import { ReactNode } from 'react'
import './globals.css'
import { CreateToastProvider } from './Hooks/ToastContext'
import { CreateInputValueProvider } from './Hooks/InputValueContext'
import { CreateThemeProviderContext } from './Hooks/ThemeContext'
import { Background } from '../app/components/Background'
import { Header } from '../app/components/Header'

export const metadata = {
  title: 'Formulário',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-br">
      <body className="overflow-y-hidden">
        <CreateThemeProviderContext>
          <CreateToastProvider>
            <CreateInputValueProvider>
              <Background>
                <Header />
                {children}
              </Background>
            </CreateInputValueProvider>
          </CreateToastProvider>
        </CreateThemeProviderContext>
      </body>
    </html>
  )
}
