import { ReactNode } from 'react'
import './globals.css'

export const metadata = {
  title: 'Formulário',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={
          ' box-border from-custom-green to-blue-500 bg-gradient-to-br'
        }
      >
        {children}
      </body>
    </html>
  )
}
